### ISSUE TITLE
acceleration training

### ISSUE THREAD

**Issue by Salterwater23** [JeffffffFu/DPSUR#1]
I want to use GPU for training, how can I change the code

**Comment by JeffffffFu** [comment]
you can change this setting "parser.add_argument('--device', type=str, default='cuda',choices=['cpu', 'cuda'])" in the main.py or you just run the code by "--device cuda"

**Comment by Salterwater23** [comment]
Thank you for your answer, I have another question, in your paper Figure 6: Acceptance probability vs. 𝛽. going to find an optimal 𝛽, how was this graph designed?
